export const USER_FIELDS = {
  id: true,
  email: true,
  name: true,
  avatar: true,
  role: true,
  phone: true,
  address: true,
  createAt: true,
  updateAt: true,
  verificationCode: true,
  verificationCodeExpiresAt: true,
  isVerified: true,
  country: true,
} as const;

export const VACCINE_FIELDS = {
  id: true,
  userId: true,
  vaccineName: true,
  image: true,
  location: true,
  description: true,
  price: true,
  batchNumber: true,
  certificate: true,
  createdAt: true,
  updatedAt: true,
  remainingQuantity: true,
  expirationDate: true,
  manufacturerId: true,
  supplierId: true,
  sideEffect: true,
} as const;
